stages:
  - stage: validate
    displayName: 'Validation'
    dependsOn: []
    jobs:
      - job: 'Windows'
        pool:
          vmImage: 'windows-latest'

        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          - task: CmdLine@1
            displayName: 'Set Token'
            inputs:
              filename: echo
              arguments: '##vso[task.setvariable variable=GITHUB_TOKEN]$(GitHub.Token)'

          - task: provisionator@2
            displayName: Provision Dependencies
            inputs:
              github_token: $(GitHub.Token)
              provisioning_script: $(System.DefaultWorkingDirectory)/bot-provisioning/dependencies.csx
              provisioning_extra_args: -vv DEVDIV_PKGS_NUGET_TOKEN=$(DevDiv.NuGet.Token) SECTOOLS_PKGS_NUGET_TOKEN=$(SecTools.NuGet.Token)

          - task: MSBuild@1
            displayName: Build
            inputs:
              solution: build.proj
              msbuildVersion: "15.0"
              msbuildArguments: '/restore /p:Release=true /t:Build'

          - task: MSBuild@1
            displayName: 'Run Tests'
            inputs:
              solution: build.proj
              msbuildVersion: "15.0"
              msbuildArguments: '/p:Release=true /t:Test'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: NUnit
              testResultsFiles: '**/TestResult.xml'
            condition: succeededOrFailed()

      - job: 'MacOS'
        pool:
          vmImage: 'macOS-latest'

        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          # Using the provisionator to switch to .NET6 doesn't currently work for some reason on Mac agents -
          # it's only .NET5 and earlier SDKS listed after running it. So use the AzDO task instead.
          - task: UseDotNet@2
            displayName: 'Use .Net Core sdk 6.0.101'
            inputs:
              version: 6.0.101

          - task: NuGetAuthenticate@0

          - task: CmdLine@1
            displayName: 'Set Token'
            inputs:
              filename: echo
              arguments: '##vso[task.setvariable variable=GITHUB_TOKEN]$(GitHub.Token)'

          - task: provisionator@2
            displayName: Provision Dependencies
            inputs:
              github_token: $(GitHub.Token)
              provisioning_script: $(System.DefaultWorkingDirectory)/bot-provisioning/dependencies.csx
              provisioning_extra_args: -vv DEVDIV_PKGS_NUGET_TOKEN=$(DevDiv.NuGet.Token) SECTOOLS_PKGS_NUGET_TOKEN=$(SecTools.NuGet.Token)

          - task: MSBuild@1
            displayName: Build
            inputs:
              solution: build.proj
              msbuildVersion: "15.0"
              msbuildArguments: '/restore /p:Release=true /t:Build'

          - task: MSBuild@1
            displayName: 'Run Tests'
            inputs:
              solution: build.proj
              msbuildVersion: "15.0"
              msbuildArguments: '/p:Release=true /t:Test'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: NUnit
              testResultsFiles: '**/TestResult.xml'
            condition: succeededOrFailed()
